#ifndef POSITIONDATAFIELDTYPE_H_
#define POSITIONDATAFIELDTYPE_H_

enum PositionDataFieldType {DEDICACION_A_ID=15, FORMACION_EN_CURSO_GRADO_Y_POSGRADO=12 , MODALIDAD=14, TIPO_DE_CARGO=13, SECRETARIA_DEPARTAMENTO=21 };

#endif
